### ISSUE TITLE
Add option to mint FIAT to and burn FIAT from proxy account instead of EOA (owner)

### ISSUE THREAD

**Issue by SolcAndMe** [fiatdao/fiat-ui#205]
- People may hold funds in their proxy instead of their own accounts
- Actions check that the current account has any balances
- Some users might want to keep funds in a proxy account
- Add option to use funds in the proxy instead of current metamask account

> (but no one has requested it so we'll wait to add until then)

**Comment by 0xTARC** [comment]
closing for same reasons as this: https://github.com/fiatdao/fiat-ui/issues/351
