### ISSUE TITLE
[Manage Positions] Add visual indicator for delegated positions, positions owned by the EOA, positions owned by the proxy account

### ISSUE THREAD

**Issue by SolcAndMe** [fiatdao/fiat-ui#261]
<img width="1189" alt="Screenshot 2022-03-18 at 23 06 10" src="https://user-images.githubusercontent.com/97065474/159090939-24bff278-a77e-4c09-8cbe-884a7e33b545.png">

Grouping would be the preferred solution

**Comment by 0xTARC** [comment]
closing this since i added an adhoc fix of disabling the "Manage" button if a position isn't managed by an EOA
