### ISSUE TITLE
Enable interaction with positions not owned by a proxy

### ISSUE THREAD

**Issue by SolcAndMe** [fiatdao/fiat-ui#351]
Conversion process:
1. check that current user has a proxy deployed (if not deploy new proxy)
2. current owner of a position (e.g. the current user EOA) needs to grant a delegate to the proxy (requires a button to do so)

This task will supersede the behaviour described in https://github.com/fiatdao/fiat-ui/issues/350

**Comment by 0xTARC** [comment]
closing for now since we just show disabled button for positions created by EOA instead of proxy

if a user is smart enough to do that via code they can manage it via code

reopen if you disagree strongly, just trying to clean up less relevant issues
