### ISSUE TITLE
Update terminology around 'Price' and 'Value'

### ISSUE THREAD

**Issue by SolcAndMe** [fiatdao/fiat-ui#559]
To make it more explicit for the user we should update the following terms in 'Create Position', 'Manage Position' in the tables and detail views:

**Price:** defined as USD price of 1 collateral unit denominated in FIAT

**Price** (in Create Position detail view), Collateral Value (in table views) --> **Current Price** (hint: 'The current price of the asset as determined by the discount rate and the spot price of the underlier')

**Face Value** (in table views and in Create Position detail view) --> **Price At Maturity** (hint: 'The redeemable price of the asset at maturity as determined by the current spot price of the underlier')

**Value:** Collateral units * Price

**Collateral Value** (in Manage Position detail view) --> **Current Value** (hint: 'The current value of the asset as determined by the discount rate and the spot price of the underlier')

**Face Value** (in Manage Position detail view) --> **Value At Maturity** (hint: 'The redeemable price of the asset at maturity (aka face value) as determined by the current spot price of the underlier')

**Comment by alex0xbe0** [comment]
@elnilz to review + response later today

**Comment by alex0xbe0** [comment]
Does this replace "Asset" @jo-es ?

**Comment by alex0xbe0** [comment]
Replace Value, Face Value, Price

**Comment by alex0xbe0** [comment]
Add hints to column names

**Comment by elnilz** [comment]
@alex0xbe0 no need to add fields that currently don't exist on a page. only rename existing fields as per description above

**Comment by elnilz** [comment]
@alex0xbe0 no need to add fields that currently don't exist on a page. only rename existing fields as per description above

**Comment by alex0xbe0** [comment]
Merged - closing
