### ISSUE TITLE
Fix console error for token allowances

### ISSUE THREAD

**Issue by whoislewys** [fiatdao/fiat-ui#583]
Currently, when creating position, we try to get the erc1155 balance and erc20 balance of a token regardless of it's type
This leads to console errors when we try to fetch the erc1155 balance for an erc20 token's address, and vice versa

See L93 of `fiat-ui/pages/create-position/[collateralId]/open/index.tsx`

AC:
* Only use erc20 functions for tokens with erc20 addresses
* Only use erc1155 functions for tokens with erc1155 addresses

One potential solution would be to condense the `useERC20Allowance` & `useERC155Allowance` into one hook, `useAllowance`

**Comment by 0xTARC** [comment]
this is captured in a more recent issue
