### ISSUE TITLE
Finish underlier flows for element

### ISSUE THREAD

**Issue by alex0xbe0** [fiatdao/fiat-ui#636]
## Problem:
Currently users have to interact with bond protocols to retrieve their underlier and size up their deposits. They shouldn't have to and so we should save them that step. Also, we should start with Element collaterals only to minimize complexity because Element has the most TVL in the dapp rn

## Solution:
* Implement new tabs from the position detail view under the Collateral section: "Deposit Underlier" and "Withdraw Underlier" `buyCollateralAndModifyDebt`
* If a user is using the "Deposit Underlier" tab, call `buyCollateralAndModifyDebt` with the appropriate args
* If a user is using the "Withdraw Underlier" tab, call `sellCollateralAndModifyDebt` with the appropriate args
* If a collateral has matured, only allow collateral withdraws. In this post-maturity case, call `redeemCollateralAndModifyDebt`
* update environment flags such that the new underlier flows are only visible for element collateral types

## Additional Context
For any other questions check the docs on [Element Zaps](https://docs.fiatdao.com/protocol/collateral-vaults/element-finance-principal-token#convenience-methods-zaps) or ask in the discy

## Acceptance Criteria:
For all Element collaterals in a forked mainnet environment,
* Deposit underlier works (underlier removed from wallet, collateral increased)
* Withdraw underlier works (collateral decreased, underlier added to wallet)
* Redeem works (call for post-maturity collaterals only. collateral decreased, underlier added to wallet)
* show special summary values when user is on deposit underlier tab (re-use same summary as deposit underlier from create position page)
* show special summary values when user is on withdraw underlier tab (um what do? something similar to deposit underlier to start should be fine)

* Ensure none of this new functionality is shown for other collateral types

**Comment by 0xTARC** [comment]
taken care of in #646 #642 and #637  (quite the team effort)
