### ISSUE TITLE
Update static components styling in Fiat DApp

### ISSUE THREAD

**Issue by 0xTARC** [fiatdao/fiat-ui#647]
## Problem:
We want to refresh the app UI piece by piece

## Solution:
Update
* sidebar
* navbar
* app icon

as shown here: https://www.figma.com/file/cFuPSsfFZYhz4hzO0NrytG/FIAT-DAO---Protocol-v1?node-id=1445%3A23349

## Acceptance Criteria:
* New UI as shown in the Figma link above
* PR is opened to upstream to an integration branch `dapp-redesign`. Create that branch if it doesn't exist.

**Comment by alex0xbe0** [comment]
Branch: https://github.com/fiatdao/fiat-ui/tree/dapp-redesign

**Comment by 0xTARC** [comment]
noice
