### ISSUE TITLE
Update “Create Position” Table UI in Fiat DApp

### ISSUE THREAD

**Issue by 0xTARC** [fiatdao/fiat-ui#648]
## Problem:
We want to refresh the app UI piece by piece

## Solution:
Make UI match designs for "Create Position" page (the table of all collaterals). See designs here on the "create position" page: https://www.figma.com/file/cFuPSsfFZYhz4hzO0NrytG/FIAT-DAO---Protocol-v1?node-id=1452%3A27015

## Acceptance Criteria:
* New UI as shown in the Figma link above.
* PR is opened to upstream to an integration branch `dapp-redesign`. Create that branch if it doesn't exist.

## Additional Context:
As you update UI, make sure not to hardcode new styles. Prefer updating the base component and defining the new styles locally

For example, if there’s a new background-color for cards, don’t hardcode the new color into that instance of the card. Instead, update the base card component in `src/components/custom/card` and add the new color style in a common file like `src/styles/theme-shared.scss`

**Comment by cryptotails** [comment]
There doesn't seem to be a new design for the table in the Figma link above. @0xTARC

**Comment by cryptotails** [comment]
@0xTARC Am I good to close tickets like this one once the relevant PR is merged?
