### ISSUE TITLE
Fix MAX Collateral to Withdraw

### ISSUE THREAD

**Issue by elnilz** [fiatdao/fiat-ui#657]
## Problem:
Currently max collateral to withdraw results in a substantial leftover collateral amount in the position but no debt. when user repays all debt she should be able to withdraw all collateral

![image](https://user-images.githubusercontent.com/91206369/180483359-f27dff2c-c544-4c7f-8d3d-497804c6c73d.png)

## Solution:
Review math for MAX collateral to withdraw

## Acceptance Criteria:
* When remaining FIAT = 0, max collateral to withdraw should be = current collateral deposited (resulting in new collateral deposited = 0)

**Comment by Rudi114** [comment]
<img width="808" alt="Screen Shot 2022-07-27 at 5 21 43 PM" src="https://user-images.githubusercontent.com/46409039/181382950-ca690f17-48b4-46e0-bb13-9ebf8ca83640.png">
<img width="808" alt="Screen Shot 2022-07-27 at 5 21 43 PM" src="https://user-images.githubusercontent.com/46409039/181382950-ca690f17-48b4-46e0-bb13-9ebf8ca83640.png">
<img width="808" alt="Screen Shot 2022-07-27 at 5 21 43 PM" src="https://user-images.githubusercontent.com/46409039/181382950-ca690f17-48b4-46e0-bb13-9ebf8ca83640.png">



@elnilz Im having trouble reproducing this issue. Maybe this is specific to the DAI underlier collaterals. Im currently testing this with a USDC underlier and it seems to work as expected. I will try again with DAI when TARC has local testing setup

**Comment by Rudi114** [comment]
<img width="542" alt="Screen Shot 2022-07-28 at 12 56 39 PM" src="https://user-images.githubusercontent.com/46409039/181605393-c182ee70-6b58-4a2f-9787-628d5a1f4f71.png">

@elnilz Tried reproducing the issue using https://impersonator.xyz/ but im still seeing this work as expected

**Comment by 0xTARC** [comment]
if we repro we revisit
