### ISSUE TITLE
Cant deposit collateral nor repay FIAT in existing position

### ISSUE THREAD

**Issue by elnilz** [fiatdao/fiat-ui#659]
## Problem:
Have created a position (id 0xb6922a39c85a4e838e1499a8b7465bdca2e49491-0x0-0xd83f53860b6a24a6daea609feb6381883b7e922b) on mainnet. Now I am unable to do both adding collateral or repaying debt bc the execute button is deactivated with caption "Insufficient Balance for ePvyDAI"

![image](https://user-images.githubusercontent.com/91206369/180487787-624b2a4a-d354-4cd7-be4a-0978f44e791b.png)

![image](https://user-images.githubusercontent.com/91206369/180488053-188d6e06-6b0f-40bc-a8fd-ed0cf7f418a0.png)

Well, actually execution button is deactivated for any action on the position

## Solution:
Idk

## Acceptance Criteria:
* Should be able to deposit/withdraw/borrow/repay

**Comment by elnilz** [comment]
testing on staging.app.fiatdao.com and mainnet network.

button is not deactivated anymore but asks me to set allowance on ePyvDAI where it shouldn't:

e.g. when trying to deposit more underlier to an existing position

![image](https://user-images.githubusercontent.com/91206369/181183379-4701b44d-8c95-4a9b-ba59-f4736d0ce417.png)

or when trying to withdraw underlier from a position

![image](https://user-images.githubusercontent.com/91206369/181183673-bd83ee10-e248-484c-8f08-28929a6fce39.png)

or when trying to borrow/repay FIAT

![image](https://user-images.githubusercontent.com/91206369/181183772-6909e1ba-9ff4-4100-ae75-a472c34a7934.png)

The button caption changes to "Execute" only when hitting Withdraw (p token) from the position. once it changed to "Execute" I can also do the above without having to set allowance on ePyvDAI so I guess its just a bug in the form

**Comment by 0xTARC** [comment]
To be clear, acceptance criteria should be that each tab only asks for the necessary allowance

e.g. If depositing underlier and no underlier allowance, ask for underlier allowance
If depositing collateral and user _HAS_ collateral token allowance, don't ask for collateral token allowance when depositing
