### ISSUE TITLE
On Max Repay Withdraw Underlier, withdrawing more than is available

### ISSUE THREAD

**Issue by Rudi114** [fiatdao/fiat-ui#708]
## Problem:
This only happened a few times and is struggling to be reproduced. Sometimes when trying to repay all, the repay amount is slightly larger than the debt, causing the gas estimation to fail and transaction to revert.

## Solution:
calculateNormalDebt should be <= position.normalDebt
debt is normal debt with the accrued interest, as t=>, debt will be greater than normal debt

The best place to fix this is the maxRepay on UI input, that way a user can never attempt to repay more than their max debt

## Acceptance Criteria:
* MaxRepay is limited by normalDebt

## Additional Context 
Add any other context (links to contracts/docs, screenshots, etc.) here.

**Comment by 0xTARC** [comment]
if we repro, we revisit
